
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8081:8080"
    environment:
        - MONGO_URI=mongodb://mongodb:27017/dart_frog_newsapp
    depends_on:
      - mongodb

  filter_service:
    build: ./filter_service
    container_name: filter_service
    ports:
      - "8082:8080"
    environment:
        - MONGO_URI=mongodb://mongodb:27017/dart_frog_newsapp
    depends_on:
      - mongodb

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8083:8080"
    environment:
        - MONGO_URI=mongodb://mongodb:27017/dart_frog_newsapp
    depends_on:
      - mongodb

  news_service:
    build: ./news_service
    container_name: news_service
    ports:
      - "8084:8080"
    environment:
        - MONGO_URI=mongodb://mongodb:27017/dart_frog_newsapp
    depends_on:
      - mongodb

volumes:
  mongodb_data:
