name: auth_service
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0
  mongo_dart: ^0.10.5
  http: ^1.4.0
  xml: ^6.5.0
  google_generative_ai: ^0.4.7
  html: ^0.15.6
  uri: ^1.0.0 
  puppeteer: ^3.18.0


dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
